#!/bin/bash

# Do the same with ppc386
export FPCBIN=ppc386
export FIXES=0
$HOME/bin/linux-fpccommonup
export FIXES=1
$HOME/bin/linux-fpccommonup

# By default use ppcx64
export FPCBIN=ppcx64
export FIXES=0
$HOME/bin/linux-fpccommonup
export FIXES=1
$HOME/bin/linux-fpccommonup

if [ "X$HOSTNAME" == "Xgcc67" ] ; then
  $HOME/bin/makesnapshotfixes 
  $HOME/bin/makesnapshottrunk

  # Update source on fpcftp machine
  $HOME/scripts/allsourcezips

  # Test all RTL compilations
  export FIXES=1
  $HOME/bin/check-all-rtl.sh
  export FIXES=0
  $HOME/bin/check-all-rtl.sh

  # Finally try to generate snapshots
  $HOME/bin/all-snapshots.sh

  # Test msdos 
  $HOME/bin/test-msdos.sh

  # Test go32v2
  $HOME/bin/test-go32v2.sh

fi
