#!/bin/bash
export RELEASEVERSION=3.0.4
export TRUNKDIRNAME=trunk
export TRUNKDIR=~/pas/$TRUNKDIRNAME
export TRUNKVERSION=3.3.1
export FIXESDIRNAME=fixes
export FIXESDIR=~/pas/$FIXESDIRNAME
export FIXESVERSION=3.2.0
