#!/bin/bash
export TRUNKDIRNAME=trunk
export TRUNKDIR=~/pas/$TRUNKDIRNAME
export RELEASEVERSION=3.0.4
export TRUNKVERSION=3.3.1
export FIXESDIRNAME=fixes_3_2
export FIXESDIR=~/pas/$FIXESDIRNAME
export FIXESVERSION=3.2.0
