
BUGTEMPLATEDIR=../bugs
CONTRIBTEMPLATEDIR=../contrib

.PHONY: install

install:
	cp head.tmpl foot.tmpl $(CONTRIBTEMPLATEDIR)
	cp bhead.tmpl $(BUGTEMPLATEDIR)/head.tmpl
	cp bfoot.tmpl $(BUGTEMPLATEDIR)/foot.tmpl
