#!/usr/bin/env bash

. $HOME/bin/fpc-versions.sh

LOGFILE=~/logs/update-source-fixes-fpc.log
$HOME/scripts/updatesourcezips_fixes > $LOGFILE 2>&1
LOGFILE=~/logs/update-source-trunk-fpc.log
$HOME/scripts/updatesourcezips_trunk > $LOGFILE 2>&1
LOGFILE=~/logs/update-source-fixes-fpcbuild.log
$HOME/scripts/updatesourcezipsbuild_fixes > $LOGFILE 2>&1
LOGFILE=~/logs/update-source-trunk-fpcbuild.log
$HOME/scripts/updatesourcezipsbuild_trunk > $LOGFILE 2>&1

