#!/bin/sh
#
# Snapshot building for Free Pascal Compiler
#
set -e

# Checkout dir
CHECKOUTDIR=$HOME/snapshot/trunk
STARTPP=fpc
INSTALLCOMPILER=$HOME/bin/ppc231-arm
MAILFILE=$HOME/logs/snapshot-trunk-arm.mail
LOGFILE=$HOME/logs/snapshot-trunk-arm.log
PPCCPU=ppcrossarm
EXTRAOPT="CPU_TARGET=arm CROSSOPT=-Cfsoft"
TEST_BINUTILSPREFIX="arm-linux-"
EMULATOR="qemu-arm"
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/trunk/i386-linux
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v23/i386-linux
# LIBGDBZIP=$HOME/snapshotlibgdb/libgdb-6.2.1-i386-linux.zip

# Include common makesnapshot script
TESTSUITEOPTS=(
  "-O- -g -Cfsoft"
)
#  "-O- -Cfsse2"
#  "-O-2 -Cfsse2 -CX -XX"
#  "-O-2ppentium4 -Cfsse2 -Cppentium4"
#  "-O- -gw2"
#  "-O-3"
#  "-O-3ppentium4 -Cfsse2 -Cppentium4"
#  "-O- -Cg"
#  "-O-2 -Cg"
# )

. $HOME/scripts/makesnapshot
