#!/bin/sh
#
# Snapshot building for Free Pascal Compiler
#
set -e

# Checkout dir
CHECKOUTDIR=$HOME/snapshot/trunk
STARTPP=fpc
INSTALLCOMPILER=$HOME/bin/ppc231
MAILFILE=$HOME/logs/snapshot-trunk.mail
LOGFILE=$HOME/logs/snapshot-trunk.log
FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/trunk/i386-linux
TESTSUITEOPTS=(
  "-O-2"
)
FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v23/i386-linux
# LIBGDBZIP=$HOME/snapshotlibgdb/libgdb-6.2.1-i386-linux.zip

# Include common makesnapshot script
. $HOME/scripts/makesnapshot
