#!/bin/sh
# Generic snapshot building
#

if [ "$CHECKOUTDIR" == "" ]; then
    echo "No CHECKOUTDIR set"
    exit 1
fi

# Limit resources (64mb data, 8mb stack)
ulimit -d 65536 -s 8192

errormailaddr=jonas@freepascal.org
#errormailaddr=peter@freepascal.org

PATH=".:${HOME}/bin:/bin:/usr/bin:/usr/local/bin"
(
date

# Clean, ignore errors makefile can be broken
cd $CHECKOUTDIR
rm -rf libgdb
rm -f *.tar.gz
make distclean TEST_FPC=$STARTPP || true
make -C tests distclean TEST_FPC=$STARTPP || true

# Run cvs update
cd $CHECKOUTDIR
svn cleanup
svn up

# add needed files (libgdb.a)
if [ "$LIBGDBZIP" != "" ]; then
        cd $CHECKOUTDIR
        unzip -o ${LIBGDBZIP}
fi

# Copy fv, not needed anymore for 1.9.x
#cd $CHECKOUTDIR/../fv
#cvs up -CPd
#cd $CHECKOUTDIR
#cp -a ../fv $CHECKOUTDIR

# make the snapshot!
cd $CHECKOUTDIR
make singlezipinstall OS_TARGET=linux SNAPSHOT=1 PP=$STARTPP OPT="-Cfsse2"

# copy current compiler to bin dir
cp $CHECKOUTDIR/compiler/ppc386 $INSTALLCOMPILER

# run testsuite and store results in database
cd $CHECKOUTDIR/tests
# fpc -iV returns exitcode 1, workaround with || true
FPCVERSION=0
[ -f $INSTALLCOMPILER ] && FPCVERSION=`$INSTALLCOMPILER -iV || true`
make clean all digest uploadrun FPC=$STARTPP TEST_FPC=$INSTALLCOMPILER DIGESTVER=$FPCVERSION DIGEST=$HOME/bin/digest DOTEST=$HOME/bin/dotest TEST_OPT="-Cfsse2" OPT="-Fu/srv/fpc/home/fpc/snapshot/fpc-2.1/rtl/units/i386-linux/"
if [ "$TESTSUITEOPT" != "" ]; then
    make clean all digest uploadrun FPC=$STARTPP TEST_FPC=$INSTALLCOMPILER DIGESTVER=$FPCVERSION DIGEST=$HOME/bin/digest DOTEST=$HOME/bin/dotest TEST_OPT="$TESTSUITEOPT" OPT="-Fu/srv/fpc/home/fpc/snapshot/fpc-2.1/rtl/units/i386-linux/"
fi

# move snapshot
cd $CHECKOUTDIR
#if [ $? = 0 ]; then
#   #  FTP machine must trust this account. Copy public key to that machine
#   # if needed Everything is set
#   scp *.tar.gz ${FTPDIR}
#   if [ $? = 0 ]; then   
#     set errormailaddr = ""
#   fi
#fi

# clean up, ignore errors... Makefile can be broken
cd $CHECKOUTDIR
rm -rf libgdb
make distclean || true
make -C tests distclean TEST_FPC=$INSTALLCOMPILER || true

date
) > $LOGFILE 2>&1 </dev/null

# send result to webmaster
if [ "${errormailaddr}" != "" ]; then
        # Create email
        echo "To: ${errormailaddr}" > $MAILFILE
        echo "From: fpc@freepascal.org" >> $MAILFILE
        echo "Subject: Daily compile routine on `hostname`" >> $MAILFILE
        echo "Reply-to: bugs@freepascal.org" >> $MAILFILE
        # truncate the log to only the last 100 lines
        /usr/bin/tail -n 100 $LOGFILE >> $MAILFILE
        /usr/sbin/sendmail -f fpc@freepascal.org ${errormailaddr} < $MAILFILE >/dev/null 2>&1
fi

# End of script.
