#!/bin/sh
#
# Snapshot building for Free Pascal Compiler
#
set -e

# Checkout dir
CHECKOUTDIR=$HOME/snapshot/fpc-trunk
STARTPP=/home/fpchome/fpc/bin/ppc386_start
INSTALLCOMPILER=$HOME/bin/ppc386-231
MAILFILE=$HOME/logs/snapshot-trunk-sse2.mail
LOGFILE=$HOME/logs/snapshot-trunk-sse2.log
FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/trunk/x86_64-linux
TESTSUITEOPT="-O2 -Cfsse2"
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/trunk/i386-linux
# LIBGDBZIP=$HOME/snapshotlibgdb/libgdb-6.2.1-i386-linux.zip

# Include common makesnapshot script
. $HOME/scripts/makesnapshot-sse2
