#!/bin/sh
#
# Snapshot building for Free Pascal Compiler
#
set -e

# Checkout dir
CHECKOUTDIR=$HOME/snapshot/trunk
STARTPP=$HOME/bin/ppc220
INSTALLCOMPILER=$HOME/bin/ppc231-sse2
MAILFILE=$HOME/logs/snapshot-trunk.mail
LOGFILE=$HOME/logs/snapshot-trunk.log
#FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v23/i386-linux
TESTSUITEOPT="-O2 -Cfsse2"
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v21/i386-linux
# LIBGDBZIP=$HOME/snapshotlibgdb/libgdb-6.2.1-i386-linux.zip

# Include common makesnapshot script
. $HOME/snapshot/makesnapshot
