#!/bin/sh
#
# Snapshot building for Free Pascal Compiler
#
set -e

# Checkout dir
CHECKOUTDIR=$HOME/snapshot/fpc-2.1
STARTPP=/usr/bin/ppc386
INSTALLCOMPILER=$HOME/bin/ppc211
MAILFILE=$HOME/logs/snapshot-2.1.mail
LOGFILE=$HOME/logs/snapshot-2.1.log
FTPDIR=deadlock.et.tudelft.nl:ftp/snapshot/v21/i386-linux
TESTSUITEOPT=-OG2p3r
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v21/i386-linux
# LIBGDBZIP=$HOME/snapshotlibgdb/libgdb-6.2.1-i386-linux.zip

# Include common makesnapshot script
. $HOME/snapshot/makesnapshot
