#!/bin/sh
#
# Snapshot building for Free Pascal Compiler
#
set -e

# Checkout dir
CHECKOUTDIR=$HOME/snapshot/trunk
STARTPP=fpc
INSTALLCOMPILER=$HOME/bin/ppc231-extra
MAILFILE=$HOME/logs/snapshot-trunk-extra.mail
LOGFILE=$HOME/logs/snapshot-trunk-extra.log
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/trunk/i386-linux
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v23/i386-linux
# LIBGDBZIP=$HOME/snapshotlibgdb/libgdb-6.2.1-i386-linux.zip

# Include common makesnapshot script
TESTSUITEOPTS=(
  "-O- -g"
  "-O- -Cfsse2"
  "-O-2 -Cfsse2 -CX -XX"
  "-O-2ppentium4 -Cfsse2 -Cppentium4"
  "-O- -gw2"
  "-O-3"
  "-O-3ppentium4 -Cfsse2 -Cppentium4"
  "-O- -Cg"
  "-O-2 -Cg"
)

. $HOME/scripts/makesnapshot
