#!/bin/sh
#
# Snapshot building for Free Pascal Compiler
#
set -e

# Checkout dir
CHECKOUTDIR=$HOME/snapshot/trunk
STARTPP=fpc
INSTALLCOMPILER=$HOME/bin/ppc231-sse2
MAILFILE=$HOME/logs/snapshot-trunk-sse2.mail
LOGFILE=$HOME/logs/snapshot-trunk-sse2.log
#FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v23/i386-linux
TESTSUITEOPT="-O2 -Cfsse2"
# FTPDIR=ftpmaster.freepascal.org:ftp/snapshot/v21/i386-linux
# LIBGDBZIP=$HOME/snapshotlibgdb/libgdb-6.2.1-i386-linux.zip

# Include common makesnapshot script
. $HOME/scripts/makesnapshot
