#!/bin/sh

set -e

CHECKOUTDIR=$HOME/build
LOGFILE=$HOME/logs/updatelog.log

# Main branch
FPCDIR=$CHECKOUTDIR/main
TAG=HEAD
LOGPACKAGES='rtl compiler utils fcl packages install installer ide docs tests fv demo lazarus'

# Fixes branch
FPCDIR10=$CHECKOUTDIR/fixes
TAG10=FIXES_1_0_0
LOGPACKAGES10='rtl compiler'

# Lazarus (and possible other projects)
PROJECTSDIR=$CHECKOUTDIR/projects
PROJECTSTAG=HEAD
LOGPROJECTS='lazarus'

# CVS2CL
CVSROOT=/FPC/CVS
CVSOPT='-z3'
CVS2CL=/home/fpc/bin/cvs2cl
CVSROOTDIR=$CHECKOUTDIR/CVSROOT
CVS2CLUSERS=$CVSROOTDIR/users

# logpackages <fpcdir> <tag> <packages>
logpackages() {
  echo
  echo "Logging dir $1 with tag $2"
  echo
  # make logs subdir
  cd $1
  cvs up -d logs
  # if not the head branch then use the Follow branch option
  # else use the -b to show branch info
  if [ "$2" != HEAD ]; then
    TAGOPT="-F $2"
  else
    TAGOPT="-F trunk"
  fi
  cd $1
  for f in $3; do
    cvs up -dP $f
    # Create the changelog in the logs repository
    $CVS2CL -S -P -U $CVS2CLUSERS -g "$CVSOPT" $TAGOPT -f CLtmp $f
    # Nuke $Log: updatelogs,v $
    # Nuke Revision 1.2  2005/02/17 16:20:43  fpc
    # Nuke   * latest revs from idefix
    # Nuke seqs to overcome an always commit
    [ -f CLtmp ] && ( sed -e 's/\$[lL]og//g' CLtmp > $1/logs/Changes.$f
                      rm CLtmp )
  done
  # commit the logfiles
  cd $1/logs
  cvs $CVSOPT commit -m 'auto'
}

(
date

# Update CVSROOT
cd $CVSROOTDIR
cvs -z3 up

logpackages $FPCDIR $TAG "$LOGPACKAGES" 
# logpackages $FPCDIR10 $TAG10 "$LOGPACKAGES10"
logpackages $PROJECTSDIR $PROJECTSTAG "$LOGPROJECTS"
) > $LOGFILE 2>&1 </dev/null

