#!/bin/bash
#
# Updatesourcezips for trunk
#

WORKDIR=$HOME/pas/updatesources
DESTDIR=fpcftp:ftp/snapshot/trunk/source
CHECKOUTDIR=$WORKDIR/svn_trunk
TAG=trunk
MODULES='fpc'
ZIPNAME=fpc.zip
SUFFIX=
#ZIPPACKAGES='rtl compiler utils fcl packages ide demo'
ZIPPACKAGES=

. $HOME/scripts/updatesourcezips
