#!/bin/bash
#
# Updatesourcezips for trunk
#

WORKDIR=$HOME/pas/updatesources
DESTDIR=fpcftp:ftp/snapshot/trunk/source
CHECKOUTDIR=$WORKDIR/svnbuild_trunk
TAG=trunk
MODULES='fpcbuild'
ZIPNAME=fpcbuild.zip
SUFFIX=
#ZIPPACKAGES='rtl compiler utils fcl packages ide demo'
ZIPPACKAGES=

. $HOME/scripts/updatesourcezips
