#!/bin/sh

set -e

REPOS="fpc html fpc/trunk fpc/branches/fixes_2_0 fpcdocs/trunk"

LOGSDIR=$HOME/snapshot/logs

SVNROOT=/FPC/svn
SVNURL=file://$SVNROOT
LOGFILE=$HOME/logs/updatelogs.log

(
date

export PATH=/usr/local/bin:$PATH

cd $LOGSDIR
svn up

for r in $REPOS; do
   repos=`echo $r | sed 's+\([^/]*\)/.*+\1+'`
   branch=`echo $r | sed 's+.*/\(.*\)$+\1+'`

   if [  "$branch" == "$r" ]; then
     changes=$repos-"all.log"
   else
     changes=$repos-$branch.log
   fi
   
   echo
   echo "Creating log $changes"
   echo "  repository=$repos"
   echo "  branch=$branch"
   echo
   
   # Add non existing files
   if [ ! -f $changes ]; then
     echo > $changes
     svn add $changes
   fi
   
   # Don't include the first import in the log and write the log reverted
   # so the new entries come first
   svn log -r HEAD:2 --xml --verbose $SVNURL/$r > $changes.xml && \
     $HOME/bin/svn2cl $changes.xml > $changes || true
   rm -f $changes.xml
done

svn ci -m "Updatelogs script"

date
) > $LOGFILE 2>&1 </dev/null

