#!/bin/sh

set -e

REPOS="
fpc
fpcbuild
html
fpc/trunk:6711
fpc/branches/fixes_2_2:6711
fpc/branches/fixes_2_4:18074
fpc/branches/fixes_2_6:29398
fpc/branches/fixes_3_0:29398
fpc/branches/fixes_3_2:39628
fpcdocs/trunk
fpcbuild/trunk:392
fpcbuild/branches/fixes_2_2:392
fpcbuild/branches/fixes_2_4:675
fpcbuild/branches/fixes_2_6:881
fpcbuild/branches/fixes_3_0:1134
fpcbuild/branches/fixes_3_2:1364
fpcprojects
lazarus
lazarus/branches/fixes_0_9_24:12768
lazarus/branches/fixes_0_9_30:28810
"

SNAPSHOTDIR=/home/FPC/snapshot
LOGSDIR=$SNAPSHOTDIR/logs
SVN2CL=$SNAPSHOTDIR/bin/svn2cl

SVNROOT=/home/FPC/svn
SVNURL=file://$SVNROOT
LOGFILE=$HOME/logs/updatelogs.log

(
date

cd $LOGSDIR
svn up

for r in $REPOS; do
   repos=`echo $r | sed 's+\([^/]*\)/.*+\1+'`
   branchandrev=`echo $r | sed 's+.*/\(.*\)$+\1+'`
   startrev=`echo $branchandrev | sed 's+^.*:++'`
   branch=`echo $branchandrev | sed 's+:.*$++'`
   svnpath=`echo $r | sed 's+:.*$++'`

   if [ "$startrev" = "$branchandrev" ]; then
     startrev="2"
   fi

   if [  "$branch" = "$r" ]; then
     changes=$repos-"all.log"
   else
     changes=$repos-$branch.log
   fi
   
   echo
   echo "Creating log $changes"
   echo "  repository=$repos"
   echo "  branch=$branch"
   echo "  startrev=$startrev"
   echo
   
   # Add non existing files
   if [ ! -f $changes ]; then
     echo > $changes
     svn add $changes
   fi
   
   # Don't include the first import in the log and write the log reverted
   # so the new entries come first
   svn log -r HEAD:$startrev --xml --verbose $SVNURL/$svnpath > $changes.xml && \
     $SVN2CL $changes.xml > $changes || true
   rm -f $changes.xml
done

svn ci -m "Updatelogs script"

date
) > $LOGFILE 2>&1 </dev/null

