#!/bin/bash
#
# Updatesourcezips for trunk
#

WORKDIR=$HOME/pas/updatesources
DESTDIR=fpcftp:ftp/snapshot/v32/source
CHECKOUTDIR=$WORKDIR/svnbuild_fixes
TAG=fixes_3_2
MODULES='fpcbuild'
ZIPNAME=fpcbuild.zip
SUFFIX=
#ZIPPACKAGES='rtl compiler utils fcl packages ide demo'
ZIPPACKAGES=

. $HOME/scripts/updatesourcezips
