#!/bin/bash

# Don't stop on errors
#set -e

TESTSUITEDIR=$HOME/testsuite
INCOMINGDIR=$TESTSUITEDIR/incoming
FAILEDDIR=$TESTSUITEDIR/failed
WORKDIR=$TESTSUITEDIR/work
LOGFILE=$HOME/logs/updatetestsuite.log
TESTSOURCEDIR=$TESTSUITEDIR/tests

# processfile <file>
processfile() {
  echo
  echo "Found file $1"
  echo

  basefn=`basename $1`
  
  rm -rf $WORKDIR
  mkdir -p $WORKDIR

  cd $WORKDIR
  tar xfvz $1
  
  if [ -f dbdigest.cfg ]; then
    # remove unit paths from testsuite parameters
    sed -e 's/-Fu[^ ]*//' < dbdigest.cfg > dbdigest.cfg.new
    mv dbdigest.cfg.new dbdigest.cfg
    echo "DatabaseName=TESTSUITE" >> dbdigest.cfg
    echo "UserName=FPCUser" >> dbdigest.cfg
    echo "PassWord=Shimrod" >> dbdigest.cfg
#    doesn't work if hostname contains number
#    date=`echo $1 | sed 's/[^0-9]*\([0-9]*\)[^0-9]*/\1/'`
#   next won't work if hostname contains 12 consecutive numbers, better (jonas)
    date=`echo $1 | sed 's/.*\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\).*/\1/'`
    echo "Date=$date" >> dbdigest.cfg
    echo "TestSrcDir=$TESTSOURCEDIR" >> dbdigest.cfg

    $HOME/bin/dbdigest
    err=$?
  else
    echo "ERROR: No dbdigest.cfg found!"
    err=1
  fi

  if [ $err -eq 0 ]; then
    rm -f $1
  else
    echo "ERROR: dbdigest failed, moving file $basefn to $FAILEDDIR"
    mv $1 $FAILEDDIR/$basefn
  fi
  
  echo "Done"
}


#
# First check if there are new files to process
#
FILES=`ls $INCOMINGDIR/*.tar.gz 2> /dev/null`
if [ "$FILES" = "" ]; then
  exit 0
fi

PATH=".:${HOME}/bin:/bin:/usr/bin:/usr/local/bin"
(
date

# Update sources
cd $TESTSOURCEDIR 
svn up

for f in $FILES; do
    processfile $f
done
) > $LOGFILE 2>&1 </dev/null
