#!/bin/bash
#
# Updatesourcezips for trunk
#

WORKDIR=$HOME/fpc
DESTDIR=$HOME/ftp/snapshot/trunk/source
CHECKOUTDIR=$WORKDIR/svnbuild_trunk
TAG=trunk
MODULES='fpcbuild'
SUFFIX=
#ZIPPACKAGES='rtl compiler utils fcl packages ide demo'
ZIPPACKAGES=

. $HOME/scripts/updatesourcezips
