#!/bin/sh
#
# Configuration.
#

PATH='.:/bin:/usr/bin:/usr/local/bin'
export PATH
CHECKOUTDIR=/tmp/fpc
SVNURL=http://svn.freepascal.org/svn/html
# HTMLREFDIR=/home/fpc/html-ref
FILELIST=/tmp/arch.filelist
MAILFILE=/tmp/arch.mail
MAILRECIPIENTSFILE=/home/fpc/webmaintainers

#setenv CVSOPT '-z9 -Q'
#setenv CVSOPT -z3

# Create dir and go to the dir
[ ! -d $CHECKOUTDIR ] && mkdir $CHECKOUTDIR && chmod 700 $CHECKOUTDIR
cd $CHECKOUTDIR

# remove files.
# [ -d html ] && [ -f html/Makefile ] && make distclean >& /dev/null
[ -d html ] && [ -f html/Makefile ] && make distclean
[ -d html ] && [ -f update.html ] && cp update.html html

# update files
cd $CHECKOUTDIR
svn checkout $SVNURL html
cd html
# make clean >&/dev/null
make clean
if [ $? != 0 ]; then
  echo html update failed.
  exit 1
fi
#echo Zipping html sourcecode.
rm -f ~/fpc/ftp/snapshot/html.zip
zip -q -9 -o -r ~/ftp/snapshot/html.zip * -x '*bugs/*'

#echo Starting make

# make makeidx all >& /dev/null
make makeidx all
if [ $? != 0 ]; then
  echo could not make html pages
  exit
else
  #echo made pages.
  echo made pages.
fi
# make tar >& /dev/null
make tar
if [ $? != 0 ]; then
  echo Could not make tar archive
  exit
fi
#echo Made tar.
# Move to ftp site
cp htmls.tar.gz ~/ftp/dist 
if [ $? != 0 ]; then
  echo Could not move to ftp site
  exit
fi
#echo moved to ftp site.


#
# Create our own pages with the modify.fp
#
# cd $CHECKOUTDIR/html
# make clean >&/dev/null
# make tar MODIFY=$HOME/modify.fp >& /dev/null
# cd ~/public_html
# rm -rf *
# ln -sf ~/logs logs
# ln -sf ~/lists lists
# tar xfz $CHECKOUTDIR/html/htmls.tar.gz
# mv download.html /tmp/dl.html
# sed -e s+ftp.freepascal.org+ftp.hu.freepascal.org+g -e s+mypath+pub/fpc/dist+g </tmp/dl.html >download.html
# rm /tmp/dl.html
# cp ~/upload.html ~/upload.php .
# cp ~/deadlock.gif pic/deadlock.gif
# cp ~/tudelft.gif pic/tudelft.gif
# ln -sf fpc.html index.html

# # Update mailinglists
# !don't! - they're updated using updatelists called from crontab separately!
# mkdir lists
# cd lists
# cp -ur /var/lib/mailman/archives/public/* . >& /dev/null
# cd ..

# Update online documentation
# rm -rf docs
# mkdir docs
# cd docs
# unzip -q /home/extra/ftp/pub/fpc/docs/docs-pdf.zip
# cd ..
# unzip -q /home/extra/ftp/pub/fpc/docs/doc-html.zip
# mv doc docs-html
# cp docs-html/fpctoc.html docs-html/fpchelp.html
# cp docs-html/fpctoc.html docs-html/index.html
# setenv DIFFERENT NO
# 
# rm -f $FILELIST 
# cd $CHECKOUTDIR/html
# foreach f ( *.html )
#   diff $f ${HTMLREFDIR}/$f >&/dev/null
#   if ( $? != 0 ) then
#      setenv DIFFERENT YES
#      echo '            ' $f >> $FILELIST
#   endif
# end
#echo did diff.
# 
# if ( $DIFFERENT != NO ) then
# cat > $MAILFILE <<MAILHEADER
# Reply-To: fpc@deadlock.et.tudelft.nl
# Subject: Free Pascal Web site has changed.
# 
# Hello,
# 
# This is an automated message. The WWW pages of Free Pascal have been
# modified. This is a list of changed files:
# 
# MAILHEADER
# cat $FILELIST >>$MAILFILE
# cat >>$MAILFILE <<MAILFOOTER
# 
# You can get a new copy at
#   ftp://ftp.freepascal.org/pub/fpc/dist/htmls.tar.gz
# or you can check out the new pages at
#   http://www.freepascal.org/
# 
# 
# Michael.
# MAILFOOTER
# Go !
# /usr/sbin/sendmail `cat $MAILRECIPIENTSFILE` < $MAILFILE
# if ( $? != 0 ) then
#   echo Error when sending mail.
# else
#   #echo Sent mail
# endif
# endif
# 
# rm -f $MAILFILE $FILELIST
# if ( $? != 0 ) then
#   echo Error when removing files.
# else
#   #echo removed files
#endif

# Copy current to reference directory
# if ( ! -e $HTMLREFDIR ) then
#   mkdir $HTMLREFDIR 
# endif
# cp *.html $HTMLREFDIR 
# if ( $? != 0 ) then
#   echo Error when copying files.
# else
#   #echo copied to reference dir
# endif
# 
# and remove files.
cd $CHECKOUTDIR/html
# make distclean >&/dev/null
make distclean

