#!/bin/bash
#
# Updatesourcezips for 1.1 branch
#

WORKDIR=/tmp/fpc
DESTDIR=$HOME/ftp/snapshot/lazarus
CHECKOUTDIR=$WORKDIR/cvs
TAG=HEAD
MODULES='lazarus'
SUFFIX=
ZIPPACKAGES=

. $HOME/updatesourcezips
