#!/bin/bash
#
# Updatesourcezips for 2.0.x branch
#

WORKDIR=/tmp/fpc
DESTDIR=$HOME/ftp/snapshot/v21/source
CHECKOUTDIR=$WORKDIR/svn21
TAG=trunk
MODULES='fpc'
SUFFIX=
#ZIPPACKAGES='rtl compiler utils fcl packages ide demo'
ZIPPACKAGES=

. $HOME/html/scripts/updatesourcezips
