#!/bin/sh
#
# Configuration.
#

PATH='.:/bin:/usr/bin:/usr/local/bin'
export PATH
CHECKOUTDIR=/tmp/fpc
SVNURL=http://svn.freepascal.org/svn/html
WWWDIR=/srv/fpc/www/htdocs/fpc/html
HTMLREFDIR=~/html-ref
FILELIST=/tmp/arch.filelist
MAILFILE=/tmp/arch.mail
MAILRECIPIENTSFILE=~/webmaintainers

#setenv CVSOPT '-z9 -Q'
#setenv CVSOPT -z3

# Create dir and go to the dir
[ ! -d $CHECKOUTDIR ] && mkdir $CHECKOUTDIR && chmod 700 $CHECKOUTDIR
cd $CHECKOUTDIR

rm -rf html > /dev/null 2>&1

# remove files.
# [ -d html ] && [ -f html/Makefile ] && make distclean >& /dev/null
# [ -d html ] && [ -f html/Makefile ] && make distclean
# [ -d html ] && [ -f update.html ] && cp update.html html
#
# update files
#cd $CHECKOUTDIR
# svn checkout $SVNURL html
svn export $SVNURL html
cd html
# make clean >&/dev/null
make clean
if [ $? != 0 ]; then
  echo html update failed.
  exit 1
fi
#echo Zipping html sourcecode.
rm -f ~/fpc/ftp/snapshot/html.zip
zip -q -9 -o -r ~/ftp/snapshot/html.zip * -x '*bugs/*'

#echo Starting make

# make makeidx all >& /dev/null
make makeidx all
if [ $? != 0 ]; then
  echo could not make html pages
  exit
else
  #echo made pages.
  echo made pages.
fi
# make tar >& /dev/null
make tar
if [ $? != 0 ]; then
  echo Could not make tar archive
  exit
fi
#echo Made tar.
# Move to ftp site
cp htmls.tar.gz ~/ftp/dist 
if [ $? != 0 ]; then
  echo Could not move to ftp site
  exit
fi
#echo moved to ftp site.


#
# Create our own pages with the modify.fp
#
#cd $CHECKOUTDIR/html
#make clean
# make tar MODIFY=$HOME/modify.fp >& /dev/null
#make tar MODIFY=$HOME/modify.fp
cd $WWWDIR
rm *
rm -rf contrib/*
rm -rf css/*
rm -rf down/*
rm -rf fcl/*
rm -rf gallery/*
rm -rf oldbugs/*
rm -rf packages/*
rm -rf pic/*
rm -rf rtl/*
rm -rf sf/*
rm -rf tools/*
# rm -rf *
ln -sf ~/logs logs
# ln -sf ~/lists lists
tar xfz $CHECKOUTDIR/html/htmls.tar.gz
ln -s fpc.html index.html
# mv download.html /tmp/dl.html
# sed -e s+ftp.freepascal.org+ftp.hu.freepascal.org+g -e s+mypath+pub/fpc/dist+g </tmp/dl.html >download.html
# rm /tmp/dl.html
# cp ~/upload.html ~/upload.php .
# cp ~/deadlock.gif pic/deadlock.gif
# cp ~/tudelft.gif pic/tudelft.gif
# ln -sf fpc.html index.html

# # Update mailinglists
# !don't! - they're updated using updatelists called from crontab separately!
# mkdir lists
# cd lists
# cp -ur /var/lib/mailman/archives/public/* . >& /dev/null
# cd ..

# Update online documentation
# rm -rf docs
# mkdir docs
# cd docs
# unzip -q /home/extra/ftp/pub/fpc/docs/docs-pdf.zip
# cd ..
# unzip -q /home/extra/ftp/pub/fpc/docs/doc-html.zip
# mv doc docs-html
# cp docs-html/fpctoc.html docs-html/fpchelp.html
# cp docs-html/fpctoc.html docs-html/index.html

DIFFERENT=NO

rm -f $FILELIST 
cd $CHECKOUTDIR/html
for f in *.html
 do
  diff $f ${HTMLREFDIR}/$f > /dev/null
  if [ $? != 0 ]; then
     DIFFERENT=YES
     echo '            ' $f >> $FILELIST
  fi
 done
echo did diff.
 
if [ $DIFFERENT != NO ]; then
cat > $MAILFILE <<MAILHEADER
Reply-To: fpc@ftpmaster.freepascal.org
Subject: Free Pascal Web site has changed.

Hello,

This is an automated message. The WWW pages of Free Pascal have been
modified. This is a list of changed files:

MAILHEADER
cat $FILELIST >>$MAILFILE
cat >>$MAILFILE <<MAILFOOTER

You can get a new copy at
  ftp://ftp.freepascal.org/pub/fpc/dist/htmls.tar.gz
or you can check out the new pages at
  http://www.freepascal.org/


Michael.
MAILFOOTER
# Go !
/usr/sbin/sendmail `cat $MAILRECIPIENTSFILE` < $MAILFILE
if [ $? != 0 ]; then
  echo Error when sending mail.
else
  echo Mail sent
fi
fi

rm -f $MAILFILE $FILELIST
if [ $? != 0 ]; then
  echo Error when removing files.
else
  echo Files removed
fi

Copy current to reference directory
if [ ! -e $HTMLREFDIR ]; then
  mkdir $HTMLREFDIR 
fi
cp *.html $HTMLREFDIR 
if [ $? != 0 ]; then
  echo Error when copying files.
else
  echo Files copied to reference dir
fi

# and remove files.
cd $CHECKOUTDIR/html
# make distclean >&/dev/null
make distclean

