#!/usr/bin/env bash

# i386 builds
export FPCBIN=ppc386
$HOME/bin/netbsd-fpccommonup
export FIXES=1
$HOME/bin/netbsd-fpccommonup
export FIXES=

# Now normal x86_64 builds
export FPCBIN=ppcx64
$HOME/bin/netbsd-fpccommonup
export FIXES=1
$HOME/bin/netbsd-fpccommonup
export FIXES=
$HOME/bin/makesnapshottrunk

